[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
stake_to_mint = "BootCCPwrDw4VQorf7UCibk1HSjbWRDRDTWizRPiCyb"

[programs.devnet]
stake_to_mint = "BootCCPwrDw4VQorf7UCibk1HSjbWRDRDTWizRPiCyb"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id_new.json"

[idl]
size = 1024

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
